### ISSUE TITLE
每次打开google scholar都会要求验证是不是机器人

### ISSUE THREAD

**Issue by hucorz** [JessyTsu1/google_scholar_spider#1]
如何解决呢？

**Comment by JessyTsu1** [comment]
前面接入类似2captcha的平台，判断如果弹出验证框的话就调用2captcha的服务，但我需求暂时不大所以之前没更新这个部分，之后闲的时候会加上，或者有兴趣的话可以帮我写一下～

**Comment by hucorz** [comment]
> 

其实手动也还行 :(，我发这issue的时候没去看源码，debug了后发现好像是那个函数弃用了
